# Generated by Django 3.1.2 on 2020-11-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='red', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(default='breakfast', max_length=20),
            preserve_default=False,
        ),
    ]
