# Generated by Django 3.1.2 on 2020-11-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20201106_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'verbose_name': 'Состав', 'verbose_name_plural': 'Состав'},
        ),
    ]
